version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: orange-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - orange-network

  # Redis (Optional - for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: orange-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orange-network

  # Orange Backend API
  api:
    build: .
    container_name: orange-api
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: development
      PORT: 3004
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/orange_db?schema=public
      REDIS_URL: redis://redis:6379
      # Add other environment variables as needed
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - orange-network
    command: npm start

  # Prisma Studio (Optional - for database management)
  prisma-studio:
    build: .
    container_name: orange-prisma-studio
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/orange_db?schema=public
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - orange-network
    command: npx prisma studio --port 5555 --hostname 0.0.0.0

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  orange-network:
    driver: bridge
